# Copyright (C) 2019-2021 Luai "TheBeautifulOrc" Malek

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# pylint: skip-file

### C++ tree generation module

import os
from glob import glob

Import('env', 'py_version')

# Name of the target library
target_name = ('./build/TreeGenModule'
	+ os.popen(py_version + '-config --extension-suffix').read().strip("\n"))
tree_gen_source = glob(pathname='**/*.cpp', recursive=True)

# Build target
tree_gen_module = env.SharedLibrary(target_name, tree_gen_source)